INSERT INTO Categories VALUES ('Dog')
INSERT INTO Categories VALUES ('Cat')
INSERT INTO Categories VALUES ('Chicken')
INSERT INTO Categories VALUES ('Rabbit')
INSERT INTO Categories VALUES ('Dinosaur')

INSERT INTO DietPlans VALUES ('Pescatarian', 'Tuna', 2)
INSERT INTO DietPlans VALUES ('DogFood', 'Beef', 3)
INSERT INTO DietPlans VALUES ('Vegetarian', 'Corn', 2)
INSERT INTO DietPlans VALUES ('Vegan', 'Carrots', 2)
INSERT INTO DietPlans VALUES ('Carnivore', 'Deer', 10)

INSERT INTO Employees VALUES ('Billy', 'Bob', 'billybob', 'abcde', 1, 'billybob@aol.com')
INSERT INTO Employees VALUES ('Gary', 'Henderson', 'garyhenderson', 'abc123', 2, 'gmonthehenderson@gmail.com')
INSERT INTO Employees VALUES ('Michael', 'Scott', 'mscott', 'fun123', 3, 'mscott@yahoo.com')
INSERT INTO Employees VALUES ('Laura', 'Raider', 'lauraraider', 'fghijk', 4, 'missraider@comcast.net')
INSERT INTO Employees VALUES ('Leslie', 'Knope', 'LKnope', 'Parks456', 5, 'Parksarethebest@gmail.com')

INSERT INTO Animals VALUES('Scrambles', 680, 150, 'Cuddly', 1, 0, 'Male', 'Available', 5, 5, 3)
INSERT INTO Animals VALUES('Ghost' , 80, 3, 'Loyal', 1, 1, 'Male', 'Taken', 1,2,5)
INSERT INTO Animals VALUES('Pancake', 15, 3, 'Aloof', 0, 0, 'Female', 'Available', 2, 1, 2)
INSERT INTO Animals VALUES('Popeye', 5, 2, 'Angry', 0, 1, 'Male', 'Available', 3, 3, 4)
INSERT INTO Animals VALUES('Patrice', 3, 4, 'Fast' , 1,1, 'Female', 'Available',  4, 4, 1)

INSERT INTO Rooms VALUES(1, 1)
INSERT INTO Rooms VALUES(2, 1)
INSERT INTO Rooms VALUES(3, 1)
INSERT INTO Rooms VALUES(4, 1)
INSERT INTO Rooms VALUES(5, 2)
INSERT INTO Rooms VALUES(6, 2)
INSERT INTO Rooms VALUES(7, 3)
INSERT INTO Rooms VALUES(8, 3)
INSERT INTO Rooms VALUES(9, 4)
INSERT INTO Rooms VALUES(10, 5)

INSERT INTO Addresses VALUES('5962 Briarwood', 'White Lake', 22, 24848)
INSERT INTO Addresses VALUES ('1737 Saint Delight Rd ', 'Georgetown', 49, 29440)
INSERT INTO Addresses VALUES('1088 Carpenter Dr', 'Lincolnton', 33, 28092)
INSERT INTO Addresses VALUES('809 S. Caldwell Ave', 'Newton', 40, 28658)
INSERT INTO Addresses VALUES ('N123W234 Concord Ave', 'Minneapolis', 23, 55111)

INSERT INTO Clients VALUES('Ben', 'Wyatt', 'bigben', 'gameofthronesfan', 1, 'bigben@hotmail.com')
INSERT INTO Clients VALUES ('Dwight', 'Schrute', 'BeetFarmer', 'battlestar galactica', 2, 'SchruteFarms2@yahoo.com')
INSERT INTO Clients VALUES('Frank', 'Reynolds', 'warthog', 'password1234', 3, 'hogman64@gmail.com')
INSERT INTO Clients VALUES ('Tom', 'Haverford', 'swaggytom', 'treatyoself', 4, 'chickychickyparmparm@gmail.com')
INSERT INTO Clients VALUES('Sterling', 'Archer', 'dangerloggins', 'ummphrasing', 5, 'sarcher@aol.com')
